FROM eu.gcr.io/devz-325114/graalvm-base:latest

ARG CLOJURE_VERSION=1.10.3.967
ARG CLOJURE_DOWNLOAD_URL=https://download.clojure.org/install

RUN curl -sf ${CLOJURE_DOWNLOAD_URL}/linux-install-${CLOJURE_VERSION}.sh | bash
